# Render deployment configuration for Bharat KYC App
# This file defines the services to be deployed on Render

services:
  # Main Web Service
  - type: web
    name: bharat-kyc-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: ap-south-1
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    branch: master

  # PostgreSQL Database
  - type: pserv
    name: bharat-kyc-db
    plan: starter
    runtime: postgresql
    startCommand: postgres

  # Redis Cache
  - type: redis
    name: bharat-kyc-redis
    plan: starter
    ipAllowList: []

  # Static Site (for documentation and wireframes)
  - type: web
    name: bharat-kyc-docs
    env: static
    buildCommand: echo "Static site deployment"
    staticPublishPath: ./05-Documentation
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: master
